version: '3.8'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/www/opt  # Ensure this points to your Symfony project
    ports:
      - "8000:80"  # Map host port 8000 to container port 80
    networks:
      - dev
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/mydb  # Ensure this matches your DB service

  webserver:
    image: nginx:alpine
    container_name: webserver
    volumes:
      - ./:/www/opt
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Ensure nginx.conf is properly configured
    ports:
      - "8080:80"  # NGINX exposed on host port 8080
    depends_on:
      - app
    networks:
      - dev

  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb  # Ensure this matches DATABASE_URL
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"  # Expose MySQL port
    networks:
      - dev

networks:
  dev:
    driver: bridge

volumes:
  db_data:
